# Generated by Django 3.2.7 on 2021-12-08 20:21

import bookreview.models
from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=20)),
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('socialtag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=1000)),
                ('img_link', models.URLField()),
                ('twitter', models.CharField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('meta', models.CharField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('instagram', models.CharField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('linkedin', models.CharField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('date_created', models.DateTimeField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.genre')),
            ],
        ),
    ]
