<<<<<<< HEAD
# Generated by Django 4.0 on 2021-12-09 15:06

import bookreview.models
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.7 on 2021-12-08 20:21

import bookreview.models
from django.db import migrations, models
import django.db.models
>>>>>>> fe471b657179bc51031cbb16ad6bdce9bae56b70


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=20)),
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Tag',
=======
            name='SocialTag',
>>>>>>> fe471b657179bc51031cbb16ad6bdce9bae56b70
            fields=[
                ('name', models.CharField(max_length=100)),
                ('socialtag_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=1000)),
                ('img_link', models.URLField()),
<<<<<<< HEAD
                ('twitter', models.URLField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('meta', models.URLField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('instagram', models.URLField(max_length=100, verbose_name=bookreview.models.Tag)),
                ('linkedin', models.URLField(max_length=100, verbose_name=bookreview.models.Tag)),
=======
                ('twitter', models.URLField(max_length=100, verbose_name=bookreview.models.SocialTag)),
                ('meta', models.URLField(max_length=100, verbose_name=bookreview.models.SocialTag)),
                ('instagram', models.URLField(max_length=100, verbose_name=bookreview.models.SocialTag)),
                ('linkedin', models.URLField(max_length=100, verbose_name=bookreview.models.SocialTag)),
>>>>>>> fe471b657179bc51031cbb16ad6bdce9bae56b70
                ('date_created', models.DateTimeField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.genre')),
            ],
        ),
    ]
