# Generated by Django 3.2.9 on 2021-12-14 20:08

import bookreview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name=bookreview.models.Tag),
        ),
        migrations.AlterField(
            model_name='post',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, verbose_name=bookreview.models.Tag),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta',
            field=models.CharField(blank=True, max_length=100, verbose_name=bookreview.models.Tag),
        ),
        migrations.AlterField(
            model_name='post',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name=bookreview.models.Tag),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
