# Generated by Django 3.2.7 on 2021-12-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_auto_20211214_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
