# Generated by Django 3.2.7 on 2021-12-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0003_post_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='post',
            name='twitter',
        ),
        migrations.AddField(
            model_name='post',
            name='social',
            field=models.ManyToManyField(to='bookreview.Tag'),
        ),
    ]
