# Generated by Django 3.2.7 on 2021-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0004_auto_20211219_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
